-- CONCEPTOS

select * from CONCEPTOS

INSERT INTO CONCEPTOS (DESCRIPCION, DEFINICION, TEMA) VALUES ("ONTOLOGIA","regla basada en la experiencia","VARIO")

UPDATE CONCEPTOS SET DEFINICION = "resguardo" WHERE DESCRIPCION = "CASA"

--TEMAS

select * from TEMAS

UPDATE TEMAS SET DESCRIPCION = "JUAN" WHERE DESCRIPCION = "PRUEBA"

INSERT INTO TEMAS (DESCRIPCION) VALUES("OTRA")

DELETE FROM TEMAS WHERE DESCRIPCION = "OTRA"
